version: '3'
services:
  frontend:
    build: .
    image: huna_node_quasar_vue:v1
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app:rw
    restart: "no"
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true